export enum ActionsTypes {
  REQUEST_CHAT_MESSAGES = "REQUEST_CHAT_MESSAGES",
  REQUEST_CHAT_MESSAGES_ERROR = "REQUEST_CHAT_MESSAGES_ERROR",
  REQUEST_CHAT_MESSAGES_SUCESS = "REQUEST_CHAT_MESSAGES_SUCESS",
}
